#!/bin/sh

#==============================================================================
# medl-init
# File ID: e5eca068-38e9-11e7-8341-f74d993421b0
#
# Initialise the member database
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=medl-init
VERSION=0.0.0

DB_VERSION=0 # Current database version
SQLITE=sqlite3
STD_DB="$HOME/.pir-medl/pir-medl.sqlite"

opt_database=
opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-d|--database) opt_database="$2"; shift 2 ;;
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

# msg(): Display debugging or informational message. The first argument decides 
# which verbosity level to use. If $opt_verbose (affected by -v/--verbose and 
# -q/--quiet) is lower than $1, the message is not printed. The rest of the 
# arguments are displayed with the format "$progname: $*".
msg() {
	test $opt_verbose -ge $1 || return
	shift
	echo "$progname: $*" >&2
}

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Initialise the member database.

Usage: $progname [options]

Options:

  -d SQLITE_DB, --database SQLITE_DB
    Use database SQLITE_DB instead of the default database.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

The environment variable MEDL_DB can be set to a default database.
Default: "$STD_DB"

END
	exit 0
fi

if test -n "$opt_database"; then
	db="$opt_database"
elif test -n "$MEDL_DB"; then
	db="$MEDL_DB"
else
	db="$STD_DB"
fi

if test -e "$db"; then
	echo $progname: $db: SQLite database already exists >&2
	exit 1
fi

dbdir="$(dirname "$db")"
test -d "$dbdir" || mkdir "$dbdir"

cat <<SQL_END | $SQLITE "$db" || exit 1
BEGIN TRANSACTION;
CREATE TABLE meta (
  key TEXT
    UNIQUE
    NOT NULL,
  value JSON
    CONSTRAINT meta_value_valid_json
      CHECK (json_valid(value))
);
INSERT INTO "meta" VALUES('dbversion', $DB_VERSION);
INSERT INTO "meta" VALUES('program', '"pir-medl"');
CREATE TABLE members (
  id INTEGER,
  name TEXT
    CONSTRAINT members_name_length
      CHECK (length(name) > 0)
    NOT NULL,
  address TEXT
  postcode TEXT,
  city TEXT,
  fylke INTEGER
    CONSTRAINT members_fylke_valid
      CHECK (fylke BETWEEN 1 AND 21 AND fylke <> 13)
    NOT NULL,
  email TEXT,
  phone TEXT,
  birthdate TEXT
    CONSTRAINT members_birthdate_length
      CHECK (birthdate IS NULL OR length(birthdate) = 10)
    CONSTRAINT members_birthdate_valid
      CHECK (birthdate IS NULL OR datetime(birthdate) IS NOT NULL),
  susp INTEGER
    CONSTRAINT members_susp_valid
      CHECK (susp between 0 AND 2)
    NOT NULL
);
CREATE TABLE payment (
  date TEXT
    CONSTRAINT payment_date_length
      CHECK (date IS NULL OR length(date) = 10)
    CONSTRAINT payment_date_valid
      CHECK (date IS NULL OR datetime(date) IS NOT NULL),
  userid INTEGER
);
COMMIT;
SQL_END

echo "$progname: Database $db created" >&2

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
