#!/bin/sh

#==============================================================================
# medl-init
# File ID: e5eca068-38e9-11e7-8341-f74d993421b0
#
# Initialise the member database
#
# Author: Øyvind A. Holm <sunny@sunbase.org>
# License: GNU General Public License version 2 or later.
#==============================================================================

progname=medl-init
VERSION=0.0.0

STD_DB="$HOME/.pir-medl/pir-medl.sqlite"

opt_database=
opt_help=0
opt_quiet=0
opt_verbose=0
while test -n "$1"; do
	case "$1" in
	-d|--database) opt_database="$2"; shift 2 ;;
	-h|--help) opt_help=1; shift ;;
	-q|--quiet) opt_quiet=$(($opt_quiet + 1)); shift ;;
	-v|--verbose) opt_verbose=$(($opt_verbose + 1)); shift ;;
	--version) echo $progname $VERSION; exit 0 ;;
	--) shift; break ;;
	*)
		if printf '%s\n' "$1" | grep -q ^-; then
			echo "$progname: $1: Unknown option" >&2
			exit 1
		else
			break
		fi
	break ;;
	esac
done
opt_verbose=$(($opt_verbose - $opt_quiet))

# msg(): Display debugging or informational message. The first argument decides 
# which verbosity level to use. If $opt_verbose (affected by -v/--verbose and 
# -q/--quiet) is lower than $1, the message is not printed. The rest of the 
# arguments are displayed with the format "$progname: $*".
msg() {
	test $opt_verbose -ge $1 || return
	shift
	echo "$progname: $*" >&2
}

if test "$opt_help" = "1"; then
	test $opt_verbose -gt 0 && { echo; echo $progname $VERSION; }
	cat <<END

Initialise the member database.

Usage: $progname [options]

Options:

  -d SQLITE_DB, --database SQLITE_DB
    Use database SQLITE_DB instead of the default database.
  -h, --help
    Show this help.
  -q, --quiet
    Be more quiet. Can be repeated to increase silence.
  -v, --verbose
    Increase level of verbosity. Can be repeated.
  --version
    Print version information.

The environment variable MEDL_DB can be set to a default database.
Default: "$STD_DB"

END
	exit 0
fi

if test -n "$opt_database"; then
	db="$opt_database"
elif test -n "$MEDL_DB"; then
	db="$MEDL_DB"
else
	db="$STD_DB"
fi

msg 2 db = \"$db\"

# vim: set ts=8 sw=8 sts=8 noet fo+=w tw=79 fenc=UTF-8 :
